version: '2'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build: backend/.
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGO_URL: 'mongodb://mongo:27017/identifier-project'
      NODE_ENV: 'production'

  frontend:
    build: frontend/.
    ports:
      - 8080:8080